### ISSUE TITLE
Allow multiple gem sources in create_minimal_gemfile

### ISSUE THREAD

**Issue by dobrite** [planningcenter/balto-rubocop#40]
I briefly touched on this issue in https://github.com/planningcenter/balto-rubocop/pull/39, but wanted to open a proper issue to capture it.

We're working towards using Github's Ruby gem server for our Gemfiles, which will replace the need to use Pico's PAT, among other benefits. The error in #39 states that multiple sources per Gemfile is not supported ([failing run](https://github.com/planningcenter/balto-rubocop/blob/7c464a21b9588a57971cc32bb8462dac11167e53/action/create_minimal_gemfile.rb#L42)), but as our Ruby repos move over that error will get increasingly common.

The part that I am unsure about is that Publishing's [Gemfile](https://github.com/planningcenter/publishing/blob/64d6c6244651c0eed20b0bb0e2b77d2049325f4f/Gemfile) works with balto-rubocop, despite having multiple sources, and yet repo-compliance-bot's [Gemfile](https://github.com/planningcenter/repo-compliance-bot/blob/9ab298bb8835ea6713dba3d0fdcc81348c48f2a4/Gemfile) did not ([failure](https://github.com/planningcenter/repo-compliance-bot/actions/runs/4961867304/jobs/8879196519?pr=33)). Perhaps y'all can provide more context as to why that is the case.

Ideally balto-rubocop is extended to support multiple sources in a Gemfile.

**Comment by molawson** [comment]
@dobrite Do you know which gem has multiple remotes?  (Yes, I realize that I wrote that error code, which has failed us on a couple of accounts 😬)

You're probably aware already, but that error isn't complaining about multiple sources, in general.  It's saying that it's resolved some particular gem to be specified as having two sources.  And I'm curious how a gem is ending up in that spot where something in a `Gemfile` is saying it lives both in our private GitHub Packages and publicly at rubygems.org 🤔

**Comment by dobrite** [comment]
Ah! That makes sense why Publishing is ok 👍 

It's the [Gemfile](https://github.com/planningcenter/repo-compliance-bot/blob/68bc48c32d635c6d8938f2b180043f9759d790c0/Gemfile) in repo-compliance-bot. I was trying to setup balto-rubocop and hit that error.

From running the code in a console it looks like they _all_ have 2 sources 🤔 One bit of extra information is that `additionalGems: "edna"` was added, and that one is pulling from Github's gem server. Without Edna they're all reporting as 1.

```ruby
ENV["INPUT_ADDITIONALGEMS"] = "edna" # simulate additionalGems: "edna"
parsed = Bundler::LockfileParser.new(Bundler.read_file('/Users/dave/Code/repo-compliance-bot/Gemfile.lock'))
filtered_gems = parsed.specs.select { |spec| gem_we_care_about?(spec.name) }
filtered_gems.map { |gem| [gem.name, gem.source.remotes.size] }
=> [["edna", 2], ["rubocop", 2], ["rubocop-ast", 2], ["rubocop-minitest", 2], ["rubocop-performance", 2], ["rubocop-rake", 2]]
```

**Comment by dobrite** [comment]
I'm going to close this issue since repo-compliance-bot is a SAM app, and therefore a special snowflake. Also, the issue I originally thought it was isn't the actual issue. Appreciate your time looking at this @molawson!
